name: Kenter Energy Monitor
version: "1.0.2"
slug: kenter_energy
description: "Monitor energy consumption and feed-in from Kenter API"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
init: false
services:
  - mqtt:need
schema:
  kenter_api_url: str
  kenter_client_id: str
  kenter_client_secret: str
  kenter_connection_id: str
  kenter_metering_point: str
  mqtt_host: str?
  mqtt_port: int?
  mqtt_user: str?
  mqtt_password: str?
  check_interval: int? 